Some test cases from Trigoda
nevercodealone/cypressio-sulu-rocks pull request #14
Opened 2022-04-08 12:31 UTC by TrigodaUG

I wrote 2 test cases for exercise:

rename-media.spec.ts - changes a media file name in the admin area

countartist.spec.ts - count the number of artist on the front page an compare it with a fixture for there defined amount

2022-04-18 08:20 UTC, nevercodealone commented
Very good sorry for late response i will check now

2022-04-18 08:34 UTC, nevercodealone requested changes
Hi my friend,

here are some feedback points. I hope you get them. When you have questions please ask.

Thx for your passion
Roland

2022-04-18 08:34 UTC, nevercodealone commented on cypress/integration/admin/rename-media.spec.ts
> +    cy.get('.masonry--AWozSpqC-B > li:first .media-card--D92EE5mvsd > .media--ejbY2jJ4HC > .cover--raBSTujlbG > .su-pen').click();
Ids can break. Maybe better use ".first()" on aria-label="su-pen" 

cy.get(`[aria-label="su-pen"]`).first()

2022-04-18 08:34 UTC, nevercodealone commented on cypress/integration/admin/rename-media.spec.ts
> +    renameMedia.EditField.clear();
Please chain methods .click().clear()....

2022-04-18 08:34 UTC, nevercodealone commented on cypress/integration/admin/rename-media.spec.ts
> +    cy.wait(500);
Wait for response and not for hard coded time. See example on login route

2022-04-18 08:34 UTC, nevercodealone commented on cypress/integration/artists/countartists.spec.ts
> +            cy.get('.card').should('have.length', this.ArtistCounter.artistsCount.en).then(_cards=>{
When you can please always use should and avoid callback constructs.

2022-04-18 08:34 UTC, nevercodealone commented on cypress/support/pages/rename-media.page.ts
> +    this.path = '/admin/';
There is a admin page with this path. Do we need a new one?

2022-04-23 12:40 UTC, TrigodaUG commented
Hello,

i tried to resolve the issues. Hope it is better now. One thing, yesterday, i could not finish, because the admin account on sulu.rocks didn't work any more. 

Kind regards
Elmar

2022-04-26 08:13 UTC, nevercodealone requested changes

2022-04-26 08:13 UTC, nevercodealone commented on cypress/integration/admin/rename-media.spec.ts
> +    cy.get('#\\/title').click().clear().type('Wolfsrudel.jpg').clear().type('Wolf.jpg');
Why is here a double change?

2022-04-26 08:13 UTC, nevercodealone commented on cypress/integration/artists/countartists.spec.ts
> +            cy.wrap(this.ArtistCounter.artistsCount.en).should('exist').and('gt',0);
should have length is enough. The test will wait for the element. Its better to use Cypress functions in a simple way

2022-04-26 08:13 UTC, nevercodealone commented on cypress/integration/artists/countartists.spec.ts
> +            cy.get('.card').should('have.length', this.ArtistCounter.artistsCount.en);
Why hard coded on 5. I think its better to check that there are artists

2022-04-26 08:13 UTC, nevercodealone commented on cypress/integration/artists/countartists.spec.ts
> +            cy.wrap(this.ArtistCounter.artistsCount.de).should('exist').and('gt',0);
simplify

2022-04-26 16:03 UTC, TrigodaUG commented
Hello,
i got that point and simplyfied it. 

Regarding the hard coded values in the fixture file, my idea was, to fill that with live data in a real world application, which could be a good idea to make testing it more dynamic?

The double fill was, because i first checked the page in Firefox, where ist disabled the save button, when nothing was changed. But it was not nessary in the test, so i deleted them.

Kind regards
Elmar

2022-04-27 15:18 UTC, nevercodealone reviewed
Thx

2022-05-02 22:38 UTC, merged